fix how to set pixi to path

diff --git a/publish/action.yaml b/publish/action.yaml
--- a/publish/action.yaml
+++ b/publish/action.yaml
@@ -46,21 +46,21 @@ runs:
       shell: bash
       run: |
         if command -v anaconda &>/dev/null; then
-            echo "'anaconda' command is available. Using it for upload."
-            echo "CMD=anaconda" >> $GITHUB_OUTPUT
+          echo "'anaconda' command is available. Using it for upload."
+          echo "CMD=anaconda" >> $GITHUB_OUTPUT
         elif pixi run anaconda --version &>/dev/null; then
-            echo "anaconda command is available via pixi. Using 'pixi run anaconda' for upload."
+          echo "anaconda command is available via pixi. Using 'pixi run anaconda' for upload."
           echo "CMD=pixi run anaconda" >> $GITHUB_OUTPUT
         else
             echo "Checking for 'pixi' command..."
             if command -v pixi &>/dev/null; then
-                echo "'pixi' command is available but 'anaconda' is not found. Installing anaconda-client..."
-                pixi global install anaconda-client
-                echo "Using 'pixi run anaconda' for upload after installation."
+              echo "'pixi' command is available but 'anaconda' is not found. Installing anaconda-client..."
+              pixi global install anaconda-client
+              echo "Using 'pixi run anaconda' for upload after installation."
             echo "CMD=pixi run anaconda" >> $GITHUB_OUTPUT
             else
-                echo "Neither 'anaconda' command nor 'pixi' is available. Please ensure that anaconda-client is installed and available in PATH or via pixi."
-                exit 1
+              echo "Neither 'anaconda' command nor 'pixi' is available. Please ensure that anaconda-client is installed and available in PATH or via pixi."
+              exit 1
             fi
         fi
 
